name: gha_example:GitHub Action exercise 

on:
  workflow_dispatch:
#  push:
#    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Akcja: "checkout"
      - name: Checkout code
        uses: actions/checkout@v2

      # Akcja: "docker/setup-buildx-action"
      - name: Buildx set-up
        uses: docker/setup-buildx-action@v1

      # Akcja: "docker/setup-qemu-action"
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1

      # Akcja: "docker/login-action"
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      # Akcja: "build-push-action"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: buterbrodskij/lab:ghlab10base
          platforms: linux/arm64/v8,linux/amd64 
